swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    # transport: smtp
    # username: inderjit.smartshore@gmail.com
    # password: '!@#inders098'
    # host: smtp.gmail.com
    # port: 465
    # encryption: ssl
    # auth_mode: login   
    #spool: { type: 'memory' }
